package com.kitehybrid.platform.risk.domain;

/** Finite reasons; never broker text. Capability gaps are explicit non-approvals. */
public enum RiskReason {
    APPROVED, TRADING_HALTED, RISK_DISABLED, RISK_UNCONFIGURED,
    ORDER_NOT_FOUND, ORDER_NOT_VALIDATED, ORDER_CHANGED, STORAGE_UNAVAILABLE,
    INSTRUMENT_NOT_FOUND, INSTRUMENT_NOT_TRADABLE, INSTRUMENT_REGISTRY_STALE,
    INVALID_LOT_SIZE, INVALID_TICK_SIZE, UNSUPPORTED_ORDER,
    MARKET_DATA_UNAVAILABLE, MARKET_DATA_STALE, INVALID_MARKET_PRICE,
    ORDER_QUANTITY_LIMIT, ORDER_VALUE_LIMIT, POSITION_LIMIT, EXPOSURE_LIMIT,
    BROKER_STATE_UNAVAILABLE, ACCOUNT_STATE_UNSUPPORTED, OPEN_BROKER_ORDERS,
    INSUFFICIENT_MARGIN, CONCURRENT_EXPOSURE_UNAVAILABLE, RISK_EVALUATION_ERROR,
    DAILY_LOSS_UNAVAILABLE
}
