package com.kitehybrid.platform.order.application;
import com.kitehybrid.platform.broker.application.auth.KiteAuthenticationSession; import com.kitehybrid.platform.instrument.application.InstrumentRegistry; import com.kitehybrid.platform.marketdata.application.*; import com.kitehybrid.platform.order.domain.*; import com.kitehybrid.platform.risk.application.RiskDecisionStore; import io.micrometer.core.instrument.MeterRegistry; import java.math.BigDecimal; import java.time.*; import java.util.function.*;
/** Broker-independent last-moment authorization. It observes state and records its decision only. */
public final class ExecutionSafetyPolicy {
 private final OrderExecutionProperties p; private final RuntimeExecutionArming arm; private final BooleanSupplier stop; private final KiteAuthenticationSession session; private final RiskDecisionStore risks; private final InstrumentRegistry instruments; private final LatestMarketDataStore market; private final Supplier<MarketDataHealth> health; private final OrderRepository orders; private final Clock clock; private final MeterRegistry metrics; private final ExecutionAuthorizationAuditStore audit;
 public ExecutionSafetyPolicy(OrderExecutionProperties p,RuntimeExecutionArming arm,BooleanSupplier stop,KiteAuthenticationSession session,RiskDecisionStore risks,InstrumentRegistry instruments,LatestMarketDataStore market,Supplier<MarketDataHealth> health,OrderRepository orders,Clock clock,MeterRegistry metrics,ExecutionAuthorizationAuditStore audit){this.p=p;this.arm=arm;this.stop=stop;this.session=session;this.risks=risks;this.instruments=instruments;this.market=market;this.health=health;this.orders=orders;this.clock=clock;this.metrics=metrics;this.audit=audit;}
 public ExecutionAuthorizationDecision evaluate(OrderRecord order){var now=clock.instant();var reason=check(order,now);var d=new ExecutionAuthorizationDecision(reason==ExecutionDenialReason.NONE,reason,now,order.id(),order.version(),p.policyVersion());audit.record(d);metrics.counter("execution.authorization","result",d.allowed()?"allowed":"denied").increment();if(!d.allowed())metrics.counter("execution.denied","reason",reason.name()).increment();return d;}
 private ExecutionDenialReason check(OrderRecord o,Instant now){if(!p.enabled())return ExecutionDenialReason.EXECUTION_DISABLED;if(!arm.armed(now))return ExecutionDenialReason.DISARMED;if(stop.getAsBoolean())return ExecutionDenialReason.EMERGENCY_STOP;if(o.state()!=OrderState.RISK_APPROVED)return ExecutionDenialReason.INVALID_ORDER_STATE;var r=risks.find(o.id()).orElse(null);if(r==null||!r.approved())return ExecutionDenialReason.RISK_APPROVAL_MISSING;if(r.orderVersion()!=o.version()-1)return ExecutionDenialReason.ORDER_VERSION_CHANGED;if(!r.policyVersion().equals(p.riskPolicyVersion()))return ExecutionDenialReason.RISK_POLICY_MISMATCH;if(!now.isBefore(r.evaluatedAt().plus(p.riskDecisionMaxAge())))return ExecutionDenialReason.RISK_APPROVAL_EXPIRED;if(!session.enabled()||!session.authenticated()||!session.tokenAvailable())return ExecutionDenialReason.AUTHENTICATION_UNAVAILABLE;if(instruments.findById(o.command().instrumentId()).isEmpty()||!p.allowedInstruments().contains(o.command().instrumentId()))return ExecutionDenialReason.INSTRUMENT_NOT_ALLOWED;if(o.command().quantity()>p.maxQuantity())return ExecutionDenialReason.QUANTITY_CAP_EXCEEDED;if(o.brokerCorrelationId().isEmpty())return ExecutionDenialReason.CORRELATION_MISSING;if(orders.hasDangerousUnresolvedOrders())return ExecutionDenialReason.RECONCILIATION_REQUIRED;var h=health.get();if(h==null||h.status()!=MarketDataHealth.Status.FRESH)return ExecutionDenialReason.MARKET_DATA_UNAVAILABLE;var t=market.latest(o.command().instrumentId()).orElse(null);if(t==null||t.lastPrice().signum()<=0)return ExecutionDenialReason.MARKET_DATA_UNAVAILABLE;if(!now.isBefore(t.receivedAt().plus(p.marketDataMaxAge())))return ExecutionDenialReason.MARKET_DATA_STALE;BigDecimal price=o.command().limitPrice().orElse(t.lastPrice());if(price.signum()<=0||price.multiply(BigDecimal.valueOf(o.command().quantity())).compareTo(p.maxNotional())>0)return ExecutionDenialReason.NOTIONAL_CAP_EXCEEDED;return ExecutionDenialReason.NONE;}
}
