package com.kitehybrid.platform.reconciliation.domain;

public enum ReconciliationReason {
    MATCHED, STATE_ADVANCED, BROKER_REJECTED, BROKER_CANCELLED, FILLS_OBSERVED,
    ORDER_NOT_FOUND, ORDER_IDENTITY_CONFLICT, UNKNOWN_BROKER_STATUS,
    BROKER_ORDER_MISSING, READ_FAILED, INVALID_FILL_QUANTITY, VERSION_CONFLICT,
    AMBIGUOUS_CORRELATION, CORRELATION_RECOVERED
}
